// auth
export const SET_USER_DATA = 'SIGN_IN/SET_USER_DATA';
export const REMOVE_USER_DATA = 'SIGN_IN/REMOVE_TOKEN';
export const SET_ALERT_MESSAGE = 'SIGN_IN/SET_MESSAGE';

// button
export const SET_BUTTON_STATE = 'BUTTON/SET_BUTTON_STATE';
export const BUTTON_ACTIVITY_SWITCH = 'BUTTON/SWITCH_BUTTON';
export const LOAD_BUTTON_STATE = 'BUTTON/LOAD_BUTTON_STATE';

// history
export const SET_QUERIES_HISTORY = 'HISTORY/SET_QUERIES_HISTORY';
export const DELETE_QUERIES_HISTORY = 'HISTORY/DELETE_QUERIES_HISTORY';
export const CLEAR_QUERIES_HISTORY = 'HISTORY/CLEAR_QUERIES_HISTORY';
