export const SET_USER_DATA = 'SIGN_IN/SET_USER_DATA';
export const REMOVE_USER_DATA = 'SIGN_IN/REMOVE_TOKEN';
export const SET_ALERT_MESSAGE = 'SIGN_IN/SET_MESSAGE';

//button
export const SET_BUTTON_STATE = 'BUTTON/SET_BUTTON_STATE';
export const BUTTON_ACTIVITY_SWITCH = 'BUTTON/SWITCH_BUTTON';
